# Generated by Django 5.2.5 on 2025-09-30 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('protein', 'Protein'), ('grain', 'Grain'), ('dairy', 'Dairy'), ('snack', 'Snack'), ('beverage', 'Beverage'), ('other', 'Other')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('serving_size', models.CharField(help_text='e.g., 1 cup, 100g', max_length=100)),
                ('calories', models.IntegerField()),
                ('protein', models.DecimalField(decimal_places=1, max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=1, max_digits=6)),
                ('fats', models.DecimalField(decimal_places=1, max_digits=6)),
                ('fiber', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Food Item',
                'verbose_name_plural': 'Food Items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('plan_type', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('muscle_gain', 'Muscle Gain'), ('maintenance', 'Maintenance'), ('keto', 'Keto'), ('low_carb', 'Low Carb'), ('high_protein', 'High Protein'), ('balanced', 'Balanced')], max_length=20)),
                ('duration_days', models.IntegerField(default=7, help_text='Duration in days (e.g., 7 for weekly)')),
                ('daily_calories', models.IntegerField(help_text='Target daily calories')),
                ('daily_protein', models.DecimalField(decimal_places=1, help_text='Target daily protein in grams', max_digits=6)),
                ('daily_carbs', models.DecimalField(decimal_places=1, help_text='Target daily carbs in grams', max_digits=6)),
                ('daily_fats', models.DecimalField(decimal_places=1, help_text='Target daily fats in grams', max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='meal_plans/')),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meal Plan',
                'verbose_name_plural': 'Meal Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(help_text='Day number in the plan (1-7 for weekly)')),
                ('notes', models.TextField(blank=True, help_text='Special notes for this day')),
                ('meal_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='nutrition.mealplan')),
            ],
            options={
                'verbose_name': 'Meal Plan Day',
                'verbose_name_plural': 'Meal Plan Days',
                'ordering': ['meal_plan', 'day_number'],
                'unique_together': {('meal_plan', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_calories', models.IntegerField(default=0)),
                ('total_protein', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('total_carbs', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('total_fats', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('total_fiber', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('water_intake', models.DecimalField(decimal_places=1, default=0, help_text='Water intake in liters', max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutrition Log',
                'verbose_name_plural': 'Nutrition Logs',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('post_workout', 'Post-Workout'), ('pre_workout', 'Pre-Workout')], max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('calories', models.IntegerField(help_text='Calories per serving')),
                ('protein', models.DecimalField(decimal_places=1, help_text='Protein in grams', max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=1, help_text='Carbohydrates in grams', max_digits=6)),
                ('fats', models.DecimalField(decimal_places=1, help_text='Fats in grams', max_digits=6)),
                ('fiber', models.DecimalField(blank=True, decimal_places=1, help_text='Fiber in grams', max_digits=5, null=True)),
                ('servings', models.IntegerField(default=1, help_text='Number of servings')),
                ('prep_time', models.IntegerField(help_text='Preparation time in minutes')),
                ('cook_time', models.IntegerField(help_text='Cooking time in minutes')),
                ('ingredients', models.TextField(help_text='List of ingredients (one per line)')),
                ('instructions', models.TextField(help_text='Step-by-step cooking instructions')),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_vegan', models.BooleanField(default=False)),
                ('is_gluten_free', models.BooleanField(default=False)),
                ('is_dairy_free', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True, help_text='Can other users see this recipe?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.CharField(choices=[('breakfast', 'Breakfast'), ('morning_snack', 'Morning Snack'), ('lunch', 'Lunch'), ('afternoon_snack', 'Afternoon Snack'), ('dinner', 'Dinner'), ('evening_snack', 'Evening Snack')], max_length=20)),
                ('servings', models.DecimalField(decimal_places=1, default=1.0, help_text='Number of servings', max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('meal_plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='nutrition.mealplanday')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan_recipes', to='nutrition.recipe')),
            ],
            options={
                'verbose_name': 'Meal Plan Recipe',
                'verbose_name_plural': 'Meal Plan Recipes',
                'ordering': ['meal_plan_day', 'meal_time'],
            },
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('morning_snack', 'Morning Snack'), ('lunch', 'Lunch'), ('afternoon_snack', 'Afternoon Snack'), ('dinner', 'Dinner'), ('evening_snack', 'Evening Snack')], max_length=20)),
                ('meal_name', models.CharField(help_text='Name of the meal', max_length=200)),
                ('calories', models.IntegerField()),
                ('protein', models.DecimalField(decimal_places=1, max_digits=6)),
                ('carbs', models.DecimalField(decimal_places=1, max_digits=6)),
                ('fats', models.DecimalField(decimal_places=1, max_digits=6)),
                ('servings', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='meal_logs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nutrition_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='nutrition.nutritionlog')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to='nutrition.recipe')),
            ],
            options={
                'verbose_name': 'Meal Log',
                'verbose_name_plural': 'Meal Logs',
                'ordering': ['nutrition_log', 'meal_type'],
            },
        ),
    ]
