# Generated by Django 5.2.5 on 2025-09-30 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('cardio', 'Cardio'), ('strength', 'Strength'), ('flexibility', 'Flexibility'), ('balance', 'Balance'), ('plyometric', 'Plyometric')], max_length=20)),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('legs', 'Legs'), ('core', 'Core'), ('full_body', 'Full Body')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or video link')),
                ('instructions', models.TextField(help_text='Step-by-step instructions')),
                ('tips', models.TextField(blank=True, help_text='Tips for proper form')),
                ('equipment_needed', models.CharField(blank=True, help_text='e.g., Dumbbells, Barbell, None', max_length=200)),
                ('calories_per_minute', models.DecimalField(decimal_places=2, default=5.0, help_text='Estimated calories burned per minute', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('goal', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('strength', 'Strength'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility'), ('general', 'General Fitness')], max_length=20)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('estimated_calories', models.IntegerField(help_text='Estimated calories burned')),
                ('image', models.ImageField(blank=True, null=True, upload_to='workouts/')),
                ('is_public', models.BooleanField(default=True, help_text='Can other users see this workout?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workout',
                'verbose_name_plural': 'Workouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='planned', max_length=20)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Actual duration', null=True)),
                ('calories_burned', models.IntegerField(blank=True, help_text='Actual calories burned', null=True)),
                ('difficulty_rating', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'Workout Session',
                'verbose_name_plural': 'Workout Sessions',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets_completed', models.IntegerField(default=0)),
                ('reps_completed', models.IntegerField(blank=True, null=True)),
                ('weight_used', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=6, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='workouts.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='workouts.workoutsession')),
            ],
            options={
                'verbose_name': 'Exercise Log',
                'verbose_name_plural': 'Exercise Logs',
                'ordering': ['session', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('weight', 'Max Weight'), ('reps', 'Max Reps'), ('duration', 'Longest Duration'), ('distance', 'Longest Distance')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Record value', max_digits=8)),
                ('unit', models.CharField(help_text='e.g., kg, reps, seconds, km', max_length=20)),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to='workouts.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal Record',
                'verbose_name_plural': 'Personal Records',
                'ordering': ['-achieved_at'],
                'unique_together': {('user', 'exercise', 'record_type')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Order in the workout')),
                ('sets', models.IntegerField(default=3)),
                ('reps', models.IntegerField(blank=True, help_text='Number of reps (leave blank for time-based)', null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds (for cardio/timed exercises)', null=True)),
                ('rest_time', models.IntegerField(default=60, help_text='Rest time in seconds between sets')),
                ('notes', models.TextField(blank=True, help_text='Special instructions for this exercise in this workout')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workouts.workout')),
            ],
            options={
                'verbose_name': 'Workout Exercise',
                'verbose_name_plural': 'Workout Exercises',
                'ordering': ['workout', 'order'],
                'unique_together': {('workout', 'exercise', 'order')},
            },
        ),
    ]
